services:
  db:
    image: mariadb:lts
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: thomas
      MYSQL_USER: thomas
      MYSQL_PASSWORD: thomas
    ports:
      - "3307:3306"