services:
#  thomas:
#    build:
#      context: .
#      target: development
#    container_name: "thomas"
#    env_file:
#      - ./.env
#    networks:
#      - mariadb
#    volumes:
#      - ./config/config.toml:/app/config/config.toml
#      - .:/app
#    ports:
#      - "8000:7008"
#    depends_on:
#      - db
  db:
    container_name: "mariadb"
    image: "mariadb:lts"
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_DATABASE: "thomas"
      MARIADB_USER: "thomas"
      MARIADB_PASSWORD: "thomas"
    networks:
      - mariadb

networks:
  mariadb:
    name: mariadb
